#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Invalid number of arguments"
    echo "Usage: ./assemble_link_run <name_of_assembly_file>"
else
    nasm -f macho64 $1 -o main.o
    ld -e _main -macosx_version_min 10.8 -arch x86_64 main.o -lSystem
    ./a.out
    rm main.o
fi


