#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "Invalid number of arguments"
    echo "Usage: ./assemble_link_run <name_of_assembly_file>"
    exit 1
fi

nasm -f macho64 $1 -o main.o || exit 1
exec 3>&2
exec 2> /dev/null
#TODO: Print output when ld fails
ld -e _main -macosx_version_min 10.8 -arch x86_64 main.o -lSystem || exit 1
exec 2>&3
./a.out

